name: indy_env
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - _py-xgboost-mutex=2.0=cpu_2
  - aom=3.6.0=hd77b12b_0
  - asttokens=3.0.0=py311haa95532_0
  - blas=1.0=mkl
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.10.5=h4c7d964_0
  - cairo=1.18.4=he9e932c_0
  - colorama=0.4.6=py311haa95532_0
  - comm=0.2.1=py311haa95532_0
  - contourpy=1.3.1=py311h214f63a_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - dav1d=1.2.1=h2bbff1b_0
  - debugpy=1.8.16=py311h885b0b7_0
  - decorator=5.2.1=py311haa95532_0
  - executing=2.2.1=py311haa95532_0
  - expat=2.7.1=h8ddb27b_0
  - fontconfig=2.15.0=hd211d86_0
  - fonttools=4.60.1=py311h02ab6af_0
  - freeglut=3.4.0=h8a1e904_1
  - freetype=2.13.3=h0620614_0
  - fribidi=1.0.10=h62dcd97_0
  - graphite2=1.3.14=hd77b12b_1
  - harfbuzz=10.2.0=he2f9f60_1
  - icc_rt=2022.1.0=h6049295_2
  - icu=73.1=h6c2663c_0
  - intel-openmp=2025.0.0=haa95532_1164
  - ipykernel=6.30.1=py311haa95532_0
  - ipython=9.5.0=py311haa95532_0
  - ipython_pygments_lexers=1.1.1=py311haa95532_0
  - jedi=0.19.2=py311haa95532_0
  - joblib=1.5.2=py311haa95532_0
  - jpeg=9f=ha349fce_0
  - jupyter_client=8.6.3=py311haa95532_0
  - jupyter_core=5.8.1=py311haa95532_0
  - khronos-opencl-icd-loader=2024.10.24=h2466b09_1
  - kiwisolver=1.4.8=py311h5da7b33_0
  - lcms2=2.16=h62be587_1
  - lerc=4.0.0=h5da7b33_0
  - libavif=1.1.1=h827c3e9_0
  - libboost=1.88.0=h3d2b97d_0
  - libdeflate=1.22=h5bf469e_0
  - libffi=3.4.4=hd77b12b_1
  - libglib=2.84.4=hfaec014_0
  - libiconv=1.16=h2bbff1b_3
  - libkrb5=1.21.3=h885b0b7_4
  - liblightgbm=4.6.0=cpu_h5d2ca61_6
  - libopenjpeg=2.5.4=h02ab6af_1
  - libpng=1.6.50=h46444df_0
  - libpq=17.6=h652a1e2_0
  - libsodium=1.0.20=h83e8143_0
  - libtiff=4.7.0=h404307b_0
  - libwebp-base=1.3.2=h3d04722_1
  - libxgboost=3.0.1=h585ebfc_0
  - libxml2=2.13.9=h6201b9f_0
  - libzlib=1.3.1=h02ab6af_0
  - lightgbm=4.6.0=cpu_py_6
  - lz4-c=1.9.4=h2bbff1b_1
  - matplotlib=3.10.6=py311haa95532_0
  - matplotlib-base=3.10.6=py311h43afe63_0
  - matplotlib-inline=0.1.7=py311haa95532_0
  - mkl=2025.0.0=h5da7b33_930
  - mkl-service=2.5.2=py311h0b37514_0
  - mkl_fft=2.1.1=py311h300f80d_0
  - mkl_random=1.3.0=py311ha5e6156_0
  - mysql-common=9.3.0=hf582a5b_3
  - mysql-libs=9.3.0=hc0ebf12_3
  - nest-asyncio=1.6.0=py311haa95532_0
  - numpy=2.3.4=py311hc2e1e29_0
  - numpy-base=2.3.4=py311hc851d2b_0
  - opencl-headers=2025.06.13=he0c23c2_0
  - openjpeg=2.5.4=h56d5a42_1
  - openssl=3.5.4=h725018a_0
  - packaging=25.0=py311haa95532_1
  - parso=0.8.4=py311haa95532_0
  - pcre2=10.46=h5740b90_0
  - pillow=11.3.0=py311hb328d1f_0
  - pip=25.2=pyhc872135_1
  - pixman=0.46.4=h4043f72_0
  - platformdirs=4.3.7=py311haa95532_0
  - prompt-toolkit=3.0.52=py311haa95532_1
  - prompt_toolkit=3.0.52=hd3eb1b0_1
  - psutil=7.0.0=py311h02ab6af_1
  - pure_eval=0.2.3=py311haa95532_0
  - pygments=2.19.1=py311haa95532_0
  - pyparsing=3.2.0=py311haa95532_0
  - pyqt=6.9.1=py311h12ec796_0
  - pyqt6-sip=13.10.2=py311h630b2a1_0
  - python=3.11.14=h981015d_0
  - python-dateutil=2.9.0post0=py311haa95532_2
  - pywin32=311=py311h885b0b7_0
  - pyzmq=27.1.0=py311h7149c55_0
  - qtbase=6.9.2=hd965823_2
  - qtdeclarative=6.9.2=h88b4c33_1
  - qtsvg=6.9.2=h30ace32_1
  - qttools=6.9.2=h7e7b719_1
  - qtwebchannel=6.9.2=heb02b0b_1
  - qtwebsockets=6.9.2=heb02b0b_1
  - scipy=1.16.3=py311hbd6d557_0
  - setuptools=80.9.0=py311haa95532_0
  - sip=6.12.0=py311h706e071_0
  - six=1.17.0=py311haa95532_0
  - sqlite=3.50.2=hda9a48d_1
  - stack_data=0.6.3=py311haa95532_0
  - tbb=2022.0.0=h214f63a_0
  - tbb-devel=2022.0.0=h214f63a_0
  - threadpoolctl=3.5.0=py311h746a85d_0
  - tk=8.6.15=hf199647_0
  - tornado=6.5.1=py311h827c3e9_0
  - traitlets=5.14.3=py311haa95532_0
  - typing_extensions=4.15.0=py311haa95532_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.42=haa95532_5
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py311haa95532_0
  - xz=5.6.4=h4754444_1
  - zeromq=4.3.5=h6c54ac7_1
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h56299aa_0
  - pip:
      - annotated-doc==0.0.3
      - annotated-types==0.7.0
      - anyio==4.11.0
      - atomicwrites==1.4.1
      - attrs==25.4.0
      - certifi==2025.10.5
      - charset-normalizer==3.4.4
      - click==8.3.0
      - cloudpickle==3.1.2
      - fastapi==0.121.0
      - filelock==3.20.0
      - fsspec==2025.10.0
      - fuzzywuzzy==0.18.0
      - geographiclib==2.1
      - geopy==2.4.1
      - greenlet==3.2.4
      - h11==0.16.0
      - haversine==2.9.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.1.2
      - idna==3.11
      - llvmlite==0.45.1
      - numba==0.62.1
      - pandas==2.3.3
      - pathlib-mate==1.3.2
      - prettytable==3.16.0
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - python-dotenv==1.2.1
      - pytz==2025.2
      - pyyaml==6.0.3
      - requests==2.32.5
      - scikit-learn==1.4.2
      - seaborn==0.13.2
      - shap==0.49.1
      - shellingham==1.5.4
      - slicer==0.0.8
      - sniffio==1.3.1
      - sqlalchemy==2.0.44
      - sqlalchemy-mate==2.0.0.3
      - starlette==0.49.3
      - tqdm==4.67.1
      - typer-slim==0.20.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - urllib3==2.5.0
      - uszipcode==1.0.1
      - uvicorn==0.38.0
      - wcwidth==0.2.14
      - xgboost==1.7.6
prefix: C:\Users\fabri\anaconda3\envs\indy_env
